"""Add is_active to jobs

Revision ID: 2d05d44d0238
Revises: ed0afa383e9a
Create Date: 2026-09-02 17:57:14.873060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d05d44d0238'
down_revision: Union[str, Sequence[str], None] = 'ed0afa383e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsa_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dsa_topics_id'), 'dsa_topics', ['id'], unique=False)
    op.create_table('dsa_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['dsa_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsa_problems_id'), 'dsa_problems', ['id'], unique=False)
    op.create_index(op.f('ix_dsa_problems_topic_id'), 'dsa_problems', ['topic_id'], unique=False)
    op.create_table('dsa_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['dsa_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_dsa_problem')
    )
    op.create_index(op.f('ix_dsa_progress_id'), 'dsa_progress', ['id'], unique=False)
    op.create_index(op.f('ix_dsa_progress_problem_id'), 'dsa_progress', ['problem_id'], unique=False)
    op.create_index(op.f('ix_dsa_progress_user_id'), 'dsa_progress', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_active')
    op.drop_index(op.f('ix_dsa_progress_user_id'), table_name='dsa_progress')
    op.drop_index(op.f('ix_dsa_progress_problem_id'), table_name='dsa_progress')
    op.drop_index(op.f('ix_dsa_progress_id'), table_name='dsa_progress')
    op.drop_table('dsa_progress')
    op.drop_index(op.f('ix_dsa_problems_topic_id'), table_name='dsa_problems')
    op.drop_index(op.f('ix_dsa_problems_id'), table_name='dsa_problems')
    op.drop_table('dsa_problems')
    op.drop_index(op.f('ix_dsa_topics_id'), table_name='dsa_topics')
    op.drop_table('dsa_topics')
    # ### end Alembic commands ###
