"""Add student profile fields

Revision ID: 58ca0af48ce8
Revises: b5d57a1a7d4f
Create Date: 2026-08-05 20:28:00.590988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ca0af48ce8'
down_revision: Union[str, Sequence[str], None] = 'b5d57a1a7d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('branch', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'semester')
    op.drop_column('users', 'branch')
    op.drop_column('users', 'college')
    # ### end Alembic commands ###
