"""Add role column

Revision ID: b5d57a1a7d4f
Revises: 19e5313a68ac
Create Date: 2026-08-05 20:07:08.294500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d57a1a7d4f'
down_revision: Union[str, Sequence[str], None] = '19e5313a68ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False,
            server_default="student"
        )
    )
    op.alter_column(
    "users",
    "role",
    server_default=None
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
