"""Create SQL preparation tables

Revision ID: bdf38228b353
Revises: b238f32bbe96
Create Date: 2026-09-05 02:34:52.647368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf38228b353'
down_revision: Union[str, Sequence[str], None] = 'b238f32bbe96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sql_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sql_topics_id'), 'sql_topics', ['id'], unique=False)
    op.create_table('sql_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('expected_query', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['sql_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_problems_id'), 'sql_problems', ['id'], unique=False)
    op.create_index(op.f('ix_sql_problems_topic_id'), 'sql_problems', ['topic_id'], unique=False)
    op.create_table('sql_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['sql_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_sql_problem')
    )
    op.create_index(op.f('ix_sql_progress_id'), 'sql_progress', ['id'], unique=False)
    op.create_index(op.f('ix_sql_progress_problem_id'), 'sql_progress', ['problem_id'], unique=False)
    op.create_index(op.f('ix_sql_progress_user_id'), 'sql_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sql_progress_user_id'), table_name='sql_progress')
    op.drop_index(op.f('ix_sql_progress_problem_id'), table_name='sql_progress')
    op.drop_index(op.f('ix_sql_progress_id'), table_name='sql_progress')
    op.drop_table('sql_progress')
    op.drop_index(op.f('ix_sql_problems_topic_id'), table_name='sql_problems')
    op.drop_index(op.f('ix_sql_problems_id'), table_name='sql_problems')
    op.drop_table('sql_problems')
    op.drop_index(op.f('ix_sql_topics_id'), table_name='sql_topics')
    op.drop_table('sql_topics')
    # ### end Alembic commands ###
