"""Create aptitude tables

Revision ID: d6092d90435a
Revises: 0c49db9df0fe
Create Date: 2026-09-07 16:02:46.430426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6092d90435a'
down_revision: Union[str, Sequence[str], None] = '0c49db9df0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aptitude_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_aptitude_topics_id'), 'aptitude_topics', ['id'], unique=False)
    op.create_table('aptitude_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['aptitude_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aptitude_questions_id'), 'aptitude_questions', ['id'], unique=False)
    op.create_index(op.f('ix_aptitude_questions_topic_id'), 'aptitude_questions', ['topic_id'], unique=False)
    op.create_table('aptitude_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['aptitude_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aptitude_progress_id'), 'aptitude_progress', ['id'], unique=False)
    op.create_index(op.f('ix_aptitude_progress_question_id'), 'aptitude_progress', ['question_id'], unique=False)
    op.create_index(op.f('ix_aptitude_progress_user_id'), 'aptitude_progress', ['user_id'], unique=False)
    op.alter_column('core_cs_problems', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('core_cs_problems', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('core_cs_problems', 'external_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_core_cs_progress_user_problem'), 'core_cs_progress', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_core_cs_progress_user_problem'), 'core_cs_progress', ['user_id', 'problem_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('core_cs_problems', 'external_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('core_cs_problems', 'difficulty',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('core_cs_problems', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_aptitude_progress_user_id'), table_name='aptitude_progress')
    op.drop_index(op.f('ix_aptitude_progress_question_id'), table_name='aptitude_progress')
    op.drop_index(op.f('ix_aptitude_progress_id'), table_name='aptitude_progress')
    op.drop_table('aptitude_progress')
    op.drop_index(op.f('ix_aptitude_questions_topic_id'), table_name='aptitude_questions')
    op.drop_index(op.f('ix_aptitude_questions_id'), table_name='aptitude_questions')
    op.drop_table('aptitude_questions')
    op.drop_index(op.f('ix_aptitude_topics_id'), table_name='aptitude_topics')
    op.drop_table('aptitude_topics')
    # ### end Alembic commands ###
